version: '2'
services:
  go-server:
    image: gocd/gocd-server:v25.1.0
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata/config/:/godata/config/
      - ./godata/users/:/godata/users/
  go-agent1:
    image: gocd/gocd-agent-ubuntu-22.04:v25.1.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: http://go-server:8153/go
  go-agent2:
    image: gocd/gocd-agent-ubuntu-22.04:v25.1.0
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: http://go-server:8153/go